"""add answer_fi to FaqRule

Revision ID: 3b5cd5a4977c
Revises: b7143f25824b
Create Date: 2026-06-17 18:39:23.286717

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b5cd5a4977c"
down_revision: Union[str, Sequence[str], None] = "b7143f25824b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("faq_rules", sa.Column("answer_fi", sa.Text(), nullable=True))
    op.drop_index(op.f("uq_interpretation_source_title"), table_name="interpretations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("uq_interpretation_source_title"),
        "interpretations",
        ["topic_id", "source", "title_fi"],
        unique=True,
    )
    op.drop_column("faq_rules", "answer_fi")
    # ### end Alembic commands ###
