"""add rate_type_context

Revision ID: 903b7bd6666e
Revises: cef4da1ff3bc
Create Date: 2026-07-29 20:06:07.632338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903b7bd6666e'
down_revision: Union[str, Sequence[str], None] = 'cef4da1ff3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tes_rates', sa.Column('rate_type_context', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('tes_rates_agreement_id_rate_type_wage_group_effective_from_key'), 'tes_rates', type_='unique')
    op.create_unique_constraint(None, 'tes_rates', ['agreement_id', 'rate_type', 'wage_group', 'effective_from', 'rate_type_context'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tes_rates', type_='unique')
    op.create_unique_constraint(op.f('tes_rates_agreement_id_rate_type_wage_group_effective_from_key'), 'tes_rates', ['agreement_id', 'rate_type', 'wage_group', 'effective_from'], postgresql_nulls_not_distinct=False)
    op.drop_column('tes_rates', 'rate_type_context')
    # ### end Alembic commands ###
