"""add key to agreements, add union_portals

Revision ID: c8cb118cd0c1
Revises: 22c20a842b74
Create Date: 2026-05-08 23:17:38.195915

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8cb118cd0c1"
down_revision: Union[str, Sequence[str], None] = "22c20a842b74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "union_portals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("union_id", sa.Integer(), nullable=False),
        sa.Column("catalog_url", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_scanned_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["union_id"], ["unions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("agreements", sa.Column("key", sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, "agreements", ["key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "agreements", type_="unique")
    op.drop_column("agreements", "key")
    op.drop_table("union_portals")
    # ### end Alembic commands ###
