"""add TesRate

Revision ID: cef4da1ff3bc
Revises: 3b5cd5a4977c
Create Date: 2026-07-09 21:11:52.737879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef4da1ff3bc'
down_revision: Union[str, Sequence[str], None] = '3b5cd5a4977c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tes_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(length=200), nullable=False),
    sa.Column('wage_group', sa.String(length=5), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=200), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('extracted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('clause_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clause_id'], ['tes_clauses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_id', 'rate_type', 'wage_group', 'effective_from')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tes_rates')
    # ### end Alembic commands ###
