"""add text_ru and translation timestamps to interpretations

Revision ID: d932e4da25a8
Revises: fc077d9a8cda
Create Date: 2026-05-05 21:25:39.269388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'd932e4da25a8'
down_revision: Union[str, Sequence[str], None] = 'fc077d9a8cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('interpretations', sa.Column('text_ru', sa.Text(), nullable=True))
    op.add_column('interpretations', sa.Column('translated_ru_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('interpretations', 'parsed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interpretations', 'parsed_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('interpretations', 'translated_ru_at')
    op.drop_column('interpretations', 'text_ru')
